version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: '-'
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor"]
