spring:
  application:
    name: /reporting-api
  main:
    banner-mode: 'OFF'
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/speedyteller?user=postgres&password=postgres&currentSchema=speedyteller}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres"}
  flyway:
    enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
      hibernate.default_schema: speedyteller
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
logging:
  level:
    ROOT: ${LOGGING_LEVEL_ROOT:INFO}
    com:
      speedyteller:
        reporting: ${LOGGING_COM_SPEEDYTELLER:DEBUG}
logbook:
  exclude:
    - /health
management:
  endpoints:
    web:
      base-path: ~
      exposure:
        include: info,health
server:
  port: ${SERVER_PORT:8080}
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
    context-path: /api/v3
springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    path: /swagger-ui/index.html
caching:
  spring:
    list: logins;users;transactions;customers;
    loginListTTL: 600000