spring:
  application:
    name: /reporting-api
  main:
    banner-mode: 'OFF'
  cache:
    type: redis
    redis:
      time-to-live: 600000
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      repositories:
        enabled: false
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/speedyteller?currentSchema=speedyteller}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari:
      minimum-idle: 2
      maximum-pool-size: 4
      auto-commit: false
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
    connection-fetch: lazy
  flyway:
    enabled: true
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      hibernate.default_schema: speedyteller
      ddl-auto: none
    show-sql: true
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
logging:
  level:
    ROOT: ${LOGGING_LEVEL_ROOT:INFO}
    com.speedyteller.reporting: ${LOGGING_COM_SPEEDYTELLER:DEBUG}
    org.hibernate.orm.connections.pooling: WARN
    com.zaxxer.hikari.HikariConfig: INFO
    com.zaxxer.hikari: INFO
logbook:
  exclude:
    - "/info"
    - "/health"
    - "/metrics"
management:
  endpoints:
    web:
      base-path: ~
      exposure:
        include: info,health,metrics
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v3
springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    path: /swagger-ui/index.html
  override-with-generic-response: false
security:
  jwt-expiration-time: 3599