spring:
  application:
    name: /reporting-api
  main:
    banner-mode: 'OFF'
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=speedyteller}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: zdtlD3JK56m6wTTgsNFhqzjqP
  issuer: speedyteller

logging:
  level:
    ROOT: ${LOGGING_LEVEL_ROOT:INFO}
    com:
      speedyteller:
        reporting: ${LOGGING_COM_SPEEDYTELLER:DEBUG}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
    context-path: /api/v3

info:
  app:
    name: reporting-api
    description: Reporting REST API
  build:
    groupId: com.speedyteller.reporting.api
    artifact: reporting-api-1.0.0.jar
    name: reporting-api
    version: 1.0.0
