name: Deploy


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "speedyteller-reporting-api"
          heroku_email: "dsv10@hotmail.com"
          healthcheck: "https://speedyteller-reporting-api.herokuapp.com/api/v3/health"
          delay: 10
