name: Deploy


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'
      - name: Running assemble
        run: ./gradlew assemble --no-daemon
  lint:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'
      - name: Running detekt
        run: ./gradlew detekt
  test:
    needs: [ lint ]
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'
      - name: Running tests
        run: ./gradlew test
        with:
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          JWT_ISSUER: ${{secrets.JWT_ISSUER}}
      - name: Upload Jacoco HTML Reports
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-reports
          path: ./build/jacocoHtml
          if-no-files-found: error
#  publish:
#    needs: [test]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: akhileshns/heroku-deploy@v3.12.12
#        with:
#          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#          heroku_app_name: "speedyteller-reporting-api"
#          heroku_email: "dsv10@hotmail.com"
#          healthcheck: "https://speedyteller-reporting-api.herokuapp.com/api/v3/health"
#          delay: 10
