name: Build pipeline


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  JWT_SECRET: ${{secrets.JWT_SECRET}}
  JWT_ISSUER: ${{secrets.JWT_ISSUER}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v4.1.7
      - name: setup java
        uses: actions/setup-java@v4.2.2
        with:
          distribution: temurin
          java-version: 21
          cache: 'gradle'
      - name: Running assemble
        run: ./gradlew assemble --no-daemon
  lint:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v4.1.7
      - name: setup java
        uses: actions/setup-java@v4.2.2
        with:
          distribution: temurin
          java-version: 21
          cache: 'gradle'
      - name: Running detekt
        run: ./gradlew detekt
  test:
    needs: [ lint ]
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v4.1.7
      - name: setup java
        uses: actions/setup-java@v4.2.2
        with:
          distribution: temurin
          java-version: 21
          cache: 'gradle'
      - name: Running tests
        run: ./gradlew test
      - name: Upload Jacoco HTML Reports
        uses: actions/upload-artifact@v4.3.6
        with:
          name: jacoco-reports
          path: ./build/jacocoHtml
          if-no-files-found: error

