name: "Build Pipeline"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  JAVA_VERSION: 25
  JAVA_DISTRIBUTION: temurin

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_type: [build, lint, test]

    steps:
      - name: Git clone
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Execute Job
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
        run: |
          if [ "${{ matrix.job_type }}" == "build" ]; then
            ./gradlew assemble --no-daemon
          elif [ "${{ matrix.job_type }}" == "lint" ]; then
            ./gradlew detekt
          elif [ "${{ matrix.job_type }}" == "test" ]; then
            ./gradlew test
          fi

      - name: Upload Jacoco HTML Reports (only for test job)
        if: matrix.job_type == 'test'
        uses: actions/upload-artifact@v7
        with:
          name: jacoco-reports
          path: ./build/jacocoHtml
          if-no-files-found: error